sudo: false

services:
  - docker

language: python

python:
  - "2.7"

install:
  - pip install lain-cli

script:
  - lain config save-global private_docker_registry registry.lain.local
  - lain build
  - LAIN_APPNAME=lvault
  - LAIN_IMAGE_VERSION="$(git show -s --format=%ct $TRAVIS_COMMIT)-$TRAVIS_COMMIT"
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run $ci_env --network=host --name lvault $LAIN_APPNAME:build-$LAIN_IMAGE_VERSION bash -c "sh test.sh && bash <(curl -s https://codecov.io/bash)"


after_success:
  - LAIN_APPNAME=lvault
  - LAIN_IMAGE_VERSION="$(git show -s --format=%ct $TRAVIS_COMMIT)-$TRAVIS_COMMIT"
  - if [ "$TRAVIS_TAG" != "" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
    docker tag $LAIN_APPNAME:release-$LAIN_IMAGE_VERSION laincloud/$LAIN_APPNAME:release-$LAIN_IMAGE_VERSION;
    docker tag $LAIN_APPNAME:meta-$LAIN_IMAGE_VERSION laincloud/$LAIN_APPNAME:meta-$LAIN_IMAGE_VERSION;
    docker push laincloud/$LAIN_APPNAME:release-$LAIN_IMAGE_VERSION;
    docker push laincloud/$LAIN_APPNAME:meta-$LAIN_IMAGE_VERSION;
    fi

